'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'
Namespace FacturaxionCancelacion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class Parametros
        
        Private foliosField As ParametrosFolios
        
        Private versionField As String
        
        Private codigoUsuarioProveedorField As String
        
        Private codigoUsuarioField As String
        
        Private rFCEmisorField As String
        
        Public Sub New()
            MyBase.New
            Me.versionField = "1.0"
        End Sub
        
        '''<remarks/>
        Public Property Folios() As ParametrosFolios
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CodigoUsuarioProveedor() As String
            Get
                Return Me.codigoUsuarioProveedorField
            End Get
            Set
                Me.codigoUsuarioProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CodigoUsuario() As String
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RFCEmisor() As String
            Get
                Return Me.rFCEmisorField
            End Get
            Set
                Me.rFCEmisorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class ParametrosFolios
        
        Private uUIDField() As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("UUID")>  _
        Public Property UUID() As Object()
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
End Namespace
