'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FactureHoyNT33
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class EmisionTimbradoException
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codeExceptionField As Integer
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codeException() As Integer
            Get
                Return Me.codeExceptionField
            End Get
            Set
                Me.codeExceptionField = value
                Me.RaisePropertyChanged("codeException")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseBO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private acuseField() As Byte
        
        Private arregloAcuseField()() As Byte
        
        Private cadenaOriginalField As String
        
        Private cadenaOriginalTimbreField As String
        
        Private codigoErrorField As Integer
        
        Private fechaHoraTimbradoField As Date
        
        Private fechaHoraTimbradoFieldSpecified As Boolean
        
        Private folioUDDIField As String
        
        Private isErrorField As Boolean
        
        Private isErrorFieldSpecified As Boolean
        
        Private messageField As String
        
        Private pDFField() As Byte
        
        Private rutaDescargaPDFField As String
        
        Private rutaDescargaXMLField As String
        
        Private selloDigitalEmisorField As String
        
        Private selloDigitalTimbreSATField As String
        
        Private xMLField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property acuse() As Byte()
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("acuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("arregloAcuse", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true, Order:=1)>  _
        Public Property arregloAcuse() As Byte()()
            Get
                Return Me.arregloAcuseField
            End Get
            Set
                Me.arregloAcuseField = value
                Me.RaisePropertyChanged("arregloAcuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property cadenaOriginal() As String
            Get
                Return Me.cadenaOriginalField
            End Get
            Set
                Me.cadenaOriginalField = value
                Me.RaisePropertyChanged("cadenaOriginal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property cadenaOriginalTimbre() As String
            Get
                Return Me.cadenaOriginalTimbreField
            End Get
            Set
                Me.cadenaOriginalTimbreField = value
                Me.RaisePropertyChanged("cadenaOriginalTimbre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
                Me.RaisePropertyChanged("codigoError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property fechaHoraTimbrado() As Date
            Get
                Return Me.fechaHoraTimbradoField
            End Get
            Set
                Me.fechaHoraTimbradoField = value
                Me.RaisePropertyChanged("fechaHoraTimbrado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaHoraTimbradoSpecified() As Boolean
            Get
                Return Me.fechaHoraTimbradoFieldSpecified
            End Get
            Set
                Me.fechaHoraTimbradoFieldSpecified = value
                Me.RaisePropertyChanged("fechaHoraTimbradoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property folioUDDI() As String
            Get
                Return Me.folioUDDIField
            End Get
            Set
                Me.folioUDDIField = value
                Me.RaisePropertyChanged("folioUDDI")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
                Me.RaisePropertyChanged("isError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isErrorSpecified() As Boolean
            Get
                Return Me.isErrorFieldSpecified
            End Get
            Set
                Me.isErrorFieldSpecified = value
                Me.RaisePropertyChanged("isErrorSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=9)>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
                Me.RaisePropertyChanged("PDF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property rutaDescargaPDF() As String
            Get
                Return Me.rutaDescargaPDFField
            End Get
            Set
                Me.rutaDescargaPDFField = value
                Me.RaisePropertyChanged("rutaDescargaPDF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property rutaDescargaXML() As String
            Get
                Return Me.rutaDescargaXMLField
            End Get
            Set
                Me.rutaDescargaXMLField = value
                Me.RaisePropertyChanged("rutaDescargaXML")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property selloDigitalEmisor() As String
            Get
                Return Me.selloDigitalEmisorField
            End Get
            Set
                Me.selloDigitalEmisorField = value
                Me.RaisePropertyChanged("selloDigitalEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property selloDigitalTimbreSAT() As String
            Get
                Return Me.selloDigitalTimbreSATField
            End Get
            Set
                Me.selloDigitalTimbreSATField = value
                Me.RaisePropertyChanged("selloDigitalTimbreSAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=14)>  _
        Public Property XML() As Byte()
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
                Me.RaisePropertyChanged("XML")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", ConfigurationName:="FactureHoyNT33.WsEmisionTimbrado33")>  _
    Public Interface WsEmisionTimbrado33
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FactureHoyNT33.EmisionTimbradoException), Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/EmitirTimbrar/Fault/Emi"& _ 
            "sionTimbradoException", Name:="EmisionTimbradoException"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EmitirTimbrar(ByVal request As FactureHoyNT33.EmitirTimbrarRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FactureHoyNT33.EmitirTimbrarResponse
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/RecuperarAcuseRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/RecuperarAcuseResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RecuperarAcuse(ByVal request As FactureHoyNT33.RecuperarAcuseRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FactureHoyNT33.RecuperarAcuseResponse
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/RecuperarAcuseCancelaci"& _ 
            "onRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/RecuperarAcuseCancelaci"& _ 
            "onResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RecuperarAcuseCancelacion(ByVal request As FactureHoyNT33.RecuperarAcuseCancelacionRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FactureHoyNT33.RecuperarAcuseCancelacionResponse
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionReque"& _ 
            "st", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacionRespo"& _ 
            "nse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FactureHoyNT33.EmisionTimbradoException), Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado33/CodigoConfirmacion/Faul"& _ 
            "t/EmisionTimbradoException", Name:="EmisionTimbradoException"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CodigoConfirmacion(ByVal request As FactureHoyNT33.CodigoConfirmacionRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FactureHoyNT33.CodigoConfirmacionResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrar", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idServicio As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public xml() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.idServicio = idServicio
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrarResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As FactureHoyNT33.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FactureHoyNT33.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As FactureHoyNT33.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FactureHoyNT33.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseCancelacion", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseCancelacionResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As FactureHoyNT33.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FactureHoyNT33.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CodigoConfirmacion", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class CodigoConfirmacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idServicio As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public xml() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.idServicio = idServicio
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CodigoConfirmacionResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class CodigoConfirmacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WsEmisionTimbrado33Channel
        Inherits FactureHoyNT33.WsEmisionTimbrado33, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WsEmisionTimbrado33Client
        Inherits System.ServiceModel.ClientBase(Of FactureHoyNT33.WsEmisionTimbrado33)
        Implements FactureHoyNT33.WsEmisionTimbrado33
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FactureHoyNT33_WsEmisionTimbrado33_EmitirTimbrar(ByVal request As FactureHoyNT33.EmitirTimbrarRequest) As FactureHoyNT33.EmitirTimbrarResponse Implements FactureHoyNT33.WsEmisionTimbrado33.EmitirTimbrar
            Return MyBase.Channel.EmitirTimbrar(request)
        End Function
        
        Public Function EmitirTimbrar(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte) As FactureHoyNT33.wsResponseBO
            Dim inValue As FactureHoyNT33.EmitirTimbrarRequest = New FactureHoyNT33.EmitirTimbrarRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.idServicio = idServicio
            inValue.xml = xml
            Dim retVal As FactureHoyNT33.EmitirTimbrarResponse = CType(Me,FactureHoyNT33.WsEmisionTimbrado33).EmitirTimbrar(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FactureHoyNT33_WsEmisionTimbrado33_RecuperarAcuse(ByVal request As FactureHoyNT33.RecuperarAcuseRequest) As FactureHoyNT33.RecuperarAcuseResponse Implements FactureHoyNT33.WsEmisionTimbrado33.RecuperarAcuse
            Return MyBase.Channel.RecuperarAcuse(request)
        End Function
        
        Public Function RecuperarAcuse(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String) As FactureHoyNT33.wsResponseBO
            Dim inValue As FactureHoyNT33.RecuperarAcuseRequest = New FactureHoyNT33.RecuperarAcuseRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.UUID = UUID
            Dim retVal As FactureHoyNT33.RecuperarAcuseResponse = CType(Me,FactureHoyNT33.WsEmisionTimbrado33).RecuperarAcuse(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FactureHoyNT33_WsEmisionTimbrado33_RecuperarAcuseCancelacion(ByVal request As FactureHoyNT33.RecuperarAcuseCancelacionRequest) As FactureHoyNT33.RecuperarAcuseCancelacionResponse Implements FactureHoyNT33.WsEmisionTimbrado33.RecuperarAcuseCancelacion
            Return MyBase.Channel.RecuperarAcuseCancelacion(request)
        End Function
        
        Public Function RecuperarAcuseCancelacion(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String) As FactureHoyNT33.wsResponseBO
            Dim inValue As FactureHoyNT33.RecuperarAcuseCancelacionRequest = New FactureHoyNT33.RecuperarAcuseCancelacionRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.UUID = UUID
            Dim retVal As FactureHoyNT33.RecuperarAcuseCancelacionResponse = CType(Me,FactureHoyNT33.WsEmisionTimbrado33).RecuperarAcuseCancelacion(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FactureHoyNT33_WsEmisionTimbrado33_CodigoConfirmacion(ByVal request As FactureHoyNT33.CodigoConfirmacionRequest) As FactureHoyNT33.CodigoConfirmacionResponse Implements FactureHoyNT33.WsEmisionTimbrado33.CodigoConfirmacion
            Return MyBase.Channel.CodigoConfirmacion(request)
        End Function
        
        Public Function CodigoConfirmacion(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte) As String
            Dim inValue As FactureHoyNT33.CodigoConfirmacionRequest = New FactureHoyNT33.CodigoConfirmacionRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.idServicio = idServicio
            inValue.xml = xml
            Dim retVal As FactureHoyNT33.CodigoConfirmacionResponse = CType(Me,FactureHoyNT33.WsEmisionTimbrado33).CodigoConfirmacion(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
