'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace FactureHoyObtenerServiciosProducccion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsServiciosPortBinding", [Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class WsServiciosService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private obtenerServiciosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private obtenerServiciosCanalClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.erp_s7.My.MySettings.Default.erp_s7_FactureHoyObtenerServiciosProducccion_WsServiciosService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event obtenerServiciosCompleted As obtenerServiciosCompletedEventHandler
        
        '''<remarks/>
        Public Event obtenerServiciosCanalClienteCompleted As obtenerServiciosCanalClienteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerServicios(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsServicioBO
            Dim results() As Object = Me.Invoke("obtenerServicios", New Object() {usuario, contrasenia})
            Return CType(results(0),wsServicioBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerServiciosAsync(ByVal usuario As String, ByVal contrasenia As String)
            Me.obtenerServiciosAsync(usuario, contrasenia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerServiciosAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal userState As Object)
            If (Me.obtenerServiciosOperationCompleted Is Nothing) Then
                Me.obtenerServiciosOperationCompleted = AddressOf Me.OnobtenerServiciosOperationCompleted
            End If
            Me.InvokeAsync("obtenerServicios", New Object() {usuario, contrasenia}, Me.obtenerServiciosOperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerServiciosOperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerServiciosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerServiciosCompleted(Me, New obtenerServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerServiciosCanalCliente(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rfc As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsServicioBO
            Dim results() As Object = Me.Invoke("obtenerServiciosCanalCliente", New Object() {usuario, contrasenia, rfc})
            Return CType(results(0),wsServicioBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerServiciosCanalClienteAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal rfc As String)
            Me.obtenerServiciosCanalClienteAsync(usuario, contrasenia, rfc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerServiciosCanalClienteAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal rfc As String, ByVal userState As Object)
            If (Me.obtenerServiciosCanalClienteOperationCompleted Is Nothing) Then
                Me.obtenerServiciosCanalClienteOperationCompleted = AddressOf Me.OnobtenerServiciosCanalClienteOperationCompleted
            End If
            Me.InvokeAsync("obtenerServiciosCanalCliente", New Object() {usuario, contrasenia, rfc}, Me.obtenerServiciosCanalClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerServiciosCanalClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerServiciosCanalClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerServiciosCanalClienteCompleted(Me, New obtenerServiciosCanalClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsServicioBO
        
        Private arrayField() As wsServicioBO
        
        Private cantidadCFDIField As Integer
        
        Private folioFinalField As Integer
        
        Private folioInicialField As Integer
        
        Private idProcessField As Integer
        
        Private mensajeField As String
        
        Private nombreServicioField As String
        
        Private serieField As String
        
        Private ultimoFolioUsadoField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("array", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property array() As wsServicioBO()
            Get
                Return Me.arrayField
            End Get
            Set
                Me.arrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidadCFDI() As Integer
            Get
                Return Me.cantidadCFDIField
            End Get
            Set
                Me.cantidadCFDIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property folioFinal() As Integer
            Get
                Return Me.folioFinalField
            End Get
            Set
                Me.folioFinalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property folioInicial() As Integer
            Get
                Return Me.folioInicialField
            End Get
            Set
                Me.folioInicialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idProcess() As Integer
            Get
                Return Me.idProcessField
            End Get
            Set
                Me.idProcessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombreServicio() As String
            Get
                Return Me.nombreServicioField
            End Get
            Set
                Me.nombreServicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ultimoFolioUsado() As Integer
            Get
                Return Me.ultimoFolioUsadoField
            End Get
            Set
                Me.ultimoFolioUsadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub obtenerServiciosCompletedEventHandler(ByVal sender As Object, ByVal e As obtenerServiciosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerServiciosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsServicioBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsServicioBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub obtenerServiciosCanalClienteCompletedEventHandler(ByVal sender As Object, ByVal e As obtenerServiciosCanalClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerServiciosCanalClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsServicioBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsServicioBO)
            End Get
        End Property
    End Class
End Namespace
