'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace NgEtiquetas
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EtiquetasSoap", [Namespace]:="http://erp.natural.gs/")>  _
    Partial Public Class Etiquetas
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetEtiquetaDeCajasByPedidoidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.erp_s7.My.MySettings.Default.erp_s7_NgEtiquetas_Etiqueta
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetEtiquetaDeCajasByPedidoidCompleted As GetEtiquetaDeCajasByPedidoidCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erp.natural.gs/GetEtiquetaDeCajasByPedidoid", RequestNamespace:="http://erp.natural.gs/", ResponseNamespace:="http://erp.natural.gs/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEtiquetaDeCajasByPedidoid(ByVal pedidoid As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetEtiquetaDeCajasByPedidoid", New Object() {pedidoid})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEtiquetaDeCajasByPedidoidAsync(ByVal pedidoid As Integer)
            Me.GetEtiquetaDeCajasByPedidoidAsync(pedidoid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEtiquetaDeCajasByPedidoidAsync(ByVal pedidoid As Integer, ByVal userState As Object)
            If (Me.GetEtiquetaDeCajasByPedidoidOperationCompleted Is Nothing) Then
                Me.GetEtiquetaDeCajasByPedidoidOperationCompleted = AddressOf Me.OnGetEtiquetaDeCajasByPedidoidOperationCompleted
            End If
            Me.InvokeAsync("GetEtiquetaDeCajasByPedidoid", New Object() {pedidoid}, Me.GetEtiquetaDeCajasByPedidoidOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEtiquetaDeCajasByPedidoidOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEtiquetaDeCajasByPedidoidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEtiquetaDeCajasByPedidoidCompleted(Me, New GetEtiquetaDeCajasByPedidoidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetEtiquetaDeCajasByPedidoidCompletedEventHandler(ByVal sender As Object, ByVal e As GetEtiquetaDeCajasByPedidoidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEtiquetaDeCajasByPedidoidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
