'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSFX
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.facturaxion.com/", ConfigurationName:="WSFX.TimbreFiscalDigitalSoap")>  _
    Public Interface TimbreFiscalDigitalSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarTimbre", ReplyAction:="*")>  _
        Function GenerarTimbre(ByVal request As WSFX.GenerarTimbreRequest) As WSFX.GenerarTimbreResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarTimbreLote", ReplyAction:="*")>  _
        Function GenerarTimbreLote(ByVal request As WSFX.GenerarTimbreLoteRequest) As WSFX.GenerarTimbreLoteResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/ReportarCancelacion", ReplyAction:="*")>  _
        Function ReportarCancelacion(ByVal request As WSFX.ReportarCancelacionRequest) As WSFX.ReportarCancelacionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarCFDI", ReplyAction:="*")>  _
        Function GenerarCFDI(ByVal request As WSFX.GenerarCFDIRequest) As WSFX.GenerarCFDIResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetAcuseRecepcion", ReplyAction:="*")>  _
        Function GetAcuseRecepcion(ByVal request As WSFX.GetAcuseRecepcionRequest) As WSFX.GetAcuseRecepcionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetAcuseCancelacion", ReplyAction:="*")>  _
        Function GetAcuseCancelacion(ByVal request As WSFX.GetAcuseCancelacionRequest) As WSFX.GetAcuseCancelacionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetIdSucursal", ReplyAction:="*")>  _
        Function GetIdSucursal(ByVal request As WSFX.GetIdSucursalRequest) As WSFX.GetIdSucursalResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarTimbrePrueba", ReplyAction:="*")>  _
        Function GenerarTimbrePrueba(ByVal request As WSFX.GenerarTimbrePruebaRequest) As WSFX.GenerarTimbrePruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarTimbreLotePrueba", ReplyAction:="*")>  _
        Function GenerarTimbreLotePrueba(ByVal request As WSFX.GenerarTimbreLotePruebaRequest) As WSFX.GenerarTimbreLotePruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/ReportarCancelacionPrueba", ReplyAction:="*")>  _
        Function ReportarCancelacionPrueba(ByVal request As WSFX.ReportarCancelacionPruebaRequest) As WSFX.ReportarCancelacionPruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GenerarCFDIPrueba", ReplyAction:="*")>  _
        Function GenerarCFDIPrueba(ByVal request As WSFX.GenerarCFDIPruebaRequest) As WSFX.GenerarCFDIPruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetAcuseRecepcionPrueba", ReplyAction:="*")>  _
        Function GetAcuseRecepcionPrueba(ByVal request As WSFX.GetAcuseRecepcionPruebaRequest) As WSFX.GetAcuseRecepcionPruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetAcuseCancelacionPrueba", ReplyAction:="*")>  _
        Function GetAcuseCancelacionPrueba(ByVal request As WSFX.GetAcuseCancelacionPruebaRequest) As WSFX.GetAcuseCancelacionPruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://www.facturaxion.com/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.facturaxion.com/GetIdSucursalPrueba", ReplyAction:="*")>  _
        Function GetIdSucursalPrueba(ByVal request As WSFX.GetIdSucursalPruebaRequest) As WSFX.GetIdSucursalPruebaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbre", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbreResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarTimbreResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarTimbreResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GenerarTimbreResult = GenerarTimbreResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreLoteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbreLote", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreLoteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreLoteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreLoteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xmlZip() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String, ByVal xmlZip() As Byte)
            MyBase.New
            Me.parametros = parametros
            Me.xmlZip = xmlZip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreLoteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbreLoteResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreLoteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreLoteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreLoteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarTimbreLoteResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultadoZip() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarTimbreLoteResult As Boolean, ByVal resultadoZip() As Byte)
            MyBase.New
            Me.GenerarTimbreLoteResult = GenerarTimbreLoteResult
            Me.resultadoZip = resultadoZip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReportarCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReportarCancelacion", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.ReportarCancelacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.ReportarCancelacionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class ReportarCancelacionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReportarCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReportarCancelacionResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.ReportarCancelacionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.ReportarCancelacionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class ReportarCancelacionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ReportarCancelacionResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReportarCancelacionResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.ReportarCancelacionResult = ReportarCancelacionResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarCFDI", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarCFDIResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarCFDIResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarCFDIResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GenerarCFDIResult = GenerarCFDIResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseRecepcionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseRecepcion", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseRecepcionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseRecepcionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseRecepcionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseRecepcionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseRecepcionResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseRecepcionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseRecepcionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseRecepcionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetAcuseRecepcionResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAcuseRecepcionResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetAcuseRecepcionResult = GetAcuseRecepcionResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseCancelacion", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseCancelacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseCancelacionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseCancelacionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseCancelacionResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseCancelacionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseCancelacionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseCancelacionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetAcuseCancelacionResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAcuseCancelacionResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetAcuseCancelacionResult = GetAcuseCancelacionResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIdSucursalRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIdSucursal", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetIdSucursalRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetIdSucursalRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetIdSucursalRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIdSucursalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIdSucursalResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetIdSucursalResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetIdSucursalResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetIdSucursalResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetIdSucursalResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIdSucursalResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetIdSucursalResult = GetIdSucursalResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbrePruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbrePrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbrePruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbrePruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbrePruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbrePruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbrePruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbrePruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbrePruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbrePruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarTimbrePruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarTimbrePruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GenerarTimbrePruebaResult = GenerarTimbrePruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreLotePruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbreLotePrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreLotePruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreLotePruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreLotePruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xmlZip() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String, ByVal xmlZip() As Byte)
            MyBase.New
            Me.parametros = parametros
            Me.xmlZip = xmlZip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarTimbreLotePruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarTimbreLotePruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarTimbreLotePruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarTimbreLotePruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarTimbreLotePruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarTimbreLotePruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultadoZip() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarTimbreLotePruebaResult As Boolean, ByVal resultadoZip() As Byte)
            MyBase.New
            Me.GenerarTimbreLotePruebaResult = GenerarTimbreLotePruebaResult
            Me.resultadoZip = resultadoZip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReportarCancelacionPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReportarCancelacionPrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.ReportarCancelacionPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.ReportarCancelacionPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class ReportarCancelacionPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReportarCancelacionPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ReportarCancelacionPruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.ReportarCancelacionPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.ReportarCancelacionPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class ReportarCancelacionPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ReportarCancelacionPruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReportarCancelacionPruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.ReportarCancelacionPruebaResult = ReportarCancelacionPruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarCFDIPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarCFDIPrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarCFDIPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarCFDIPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarCFDIPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GenerarCFDIPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GenerarCFDIPruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GenerarCFDIPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GenerarCFDIPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GenerarCFDIPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GenerarCFDIPruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarCFDIPruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GenerarCFDIPruebaResult = GenerarCFDIPruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseRecepcionPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseRecepcionPrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseRecepcionPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseRecepcionPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseRecepcionPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseRecepcionPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseRecepcionPruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseRecepcionPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseRecepcionPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseRecepcionPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetAcuseRecepcionPruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAcuseRecepcionPruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetAcuseRecepcionPruebaResult = GetAcuseRecepcionPruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseCancelacionPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseCancelacionPrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseCancelacionPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseCancelacionPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseCancelacionPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAcuseCancelacionPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAcuseCancelacionPruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetAcuseCancelacionPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetAcuseCancelacionPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetAcuseCancelacionPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetAcuseCancelacionPruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAcuseCancelacionPruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetAcuseCancelacionPruebaResult = GetAcuseCancelacionPruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIdSucursalPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIdSucursalPrueba", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetIdSucursalPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetIdSucursalPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetIdSucursalPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametros As String)
            MyBase.New
            Me.parametros = parametros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIdSucursalPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIdSucursalPruebaResponse", [Namespace]:="http://www.facturaxion.com/", Order:=0)>  _
        Public Body As WSFX.GetIdSucursalPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFX.GetIdSucursalPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.facturaxion.com/")>  _
    Partial Public Class GetIdSucursalPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetIdSucursalPruebaResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public resultado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIdSucursalPruebaResult As Boolean, ByVal resultado As String)
            MyBase.New
            Me.GetIdSucursalPruebaResult = GetIdSucursalPruebaResult
            Me.resultado = resultado
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TimbreFiscalDigitalSoapChannel
        Inherits WSFX.TimbreFiscalDigitalSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TimbreFiscalDigitalSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSFX.TimbreFiscalDigitalSoap)
        Implements WSFX.TimbreFiscalDigitalSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarTimbre(ByVal request As WSFX.GenerarTimbreRequest) As WSFX.GenerarTimbreResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarTimbre
            Return MyBase.Channel.GenerarTimbre(request)
        End Function
        
        Public Function GenerarTimbre(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GenerarTimbreRequest = New WSFX.GenerarTimbreRequest()
            inValue.Body = New WSFX.GenerarTimbreRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GenerarTimbreResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarTimbre(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GenerarTimbreResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarTimbreLote(ByVal request As WSFX.GenerarTimbreLoteRequest) As WSFX.GenerarTimbreLoteResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarTimbreLote
            Return MyBase.Channel.GenerarTimbreLote(request)
        End Function
        
        Public Function GenerarTimbreLote(ByVal parametros As String, ByVal xmlZip() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef resultadoZip() As Byte) As Boolean
            Dim inValue As WSFX.GenerarTimbreLoteRequest = New WSFX.GenerarTimbreLoteRequest()
            inValue.Body = New WSFX.GenerarTimbreLoteRequestBody()
            inValue.Body.parametros = parametros
            inValue.Body.xmlZip = xmlZip
            Dim retVal As WSFX.GenerarTimbreLoteResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarTimbreLote(inValue)
            resultadoZip = retVal.Body.resultadoZip
            Return retVal.Body.GenerarTimbreLoteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_ReportarCancelacion(ByVal request As WSFX.ReportarCancelacionRequest) As WSFX.ReportarCancelacionResponse Implements WSFX.TimbreFiscalDigitalSoap.ReportarCancelacion
            Return MyBase.Channel.ReportarCancelacion(request)
        End Function
        
        Public Function ReportarCancelacion(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.ReportarCancelacionRequest = New WSFX.ReportarCancelacionRequest()
            inValue.Body = New WSFX.ReportarCancelacionRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.ReportarCancelacionResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).ReportarCancelacion(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.ReportarCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarCFDI(ByVal request As WSFX.GenerarCFDIRequest) As WSFX.GenerarCFDIResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarCFDI
            Return MyBase.Channel.GenerarCFDI(request)
        End Function
        
        Public Function GenerarCFDI(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GenerarCFDIRequest = New WSFX.GenerarCFDIRequest()
            inValue.Body = New WSFX.GenerarCFDIRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GenerarCFDIResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarCFDI(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GenerarCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetAcuseRecepcion(ByVal request As WSFX.GetAcuseRecepcionRequest) As WSFX.GetAcuseRecepcionResponse Implements WSFX.TimbreFiscalDigitalSoap.GetAcuseRecepcion
            Return MyBase.Channel.GetAcuseRecepcion(request)
        End Function
        
        Public Function GetAcuseRecepcion(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetAcuseRecepcionRequest = New WSFX.GetAcuseRecepcionRequest()
            inValue.Body = New WSFX.GetAcuseRecepcionRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetAcuseRecepcionResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetAcuseRecepcion(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetAcuseRecepcionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetAcuseCancelacion(ByVal request As WSFX.GetAcuseCancelacionRequest) As WSFX.GetAcuseCancelacionResponse Implements WSFX.TimbreFiscalDigitalSoap.GetAcuseCancelacion
            Return MyBase.Channel.GetAcuseCancelacion(request)
        End Function
        
        Public Function GetAcuseCancelacion(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetAcuseCancelacionRequest = New WSFX.GetAcuseCancelacionRequest()
            inValue.Body = New WSFX.GetAcuseCancelacionRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetAcuseCancelacionResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetAcuseCancelacion(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetAcuseCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetIdSucursal(ByVal request As WSFX.GetIdSucursalRequest) As WSFX.GetIdSucursalResponse Implements WSFX.TimbreFiscalDigitalSoap.GetIdSucursal
            Return MyBase.Channel.GetIdSucursal(request)
        End Function
        
        Public Function GetIdSucursal(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetIdSucursalRequest = New WSFX.GetIdSucursalRequest()
            inValue.Body = New WSFX.GetIdSucursalRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetIdSucursalResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetIdSucursal(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetIdSucursalResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarTimbrePrueba(ByVal request As WSFX.GenerarTimbrePruebaRequest) As WSFX.GenerarTimbrePruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarTimbrePrueba
            Return MyBase.Channel.GenerarTimbrePrueba(request)
        End Function
        
        Public Function GenerarTimbrePrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GenerarTimbrePruebaRequest = New WSFX.GenerarTimbrePruebaRequest()
            inValue.Body = New WSFX.GenerarTimbrePruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GenerarTimbrePruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarTimbrePrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GenerarTimbrePruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarTimbreLotePrueba(ByVal request As WSFX.GenerarTimbreLotePruebaRequest) As WSFX.GenerarTimbreLotePruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarTimbreLotePrueba
            Return MyBase.Channel.GenerarTimbreLotePrueba(request)
        End Function
        
        Public Function GenerarTimbreLotePrueba(ByVal parametros As String, ByVal xmlZip() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef resultadoZip() As Byte) As Boolean
            Dim inValue As WSFX.GenerarTimbreLotePruebaRequest = New WSFX.GenerarTimbreLotePruebaRequest()
            inValue.Body = New WSFX.GenerarTimbreLotePruebaRequestBody()
            inValue.Body.parametros = parametros
            inValue.Body.xmlZip = xmlZip
            Dim retVal As WSFX.GenerarTimbreLotePruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarTimbreLotePrueba(inValue)
            resultadoZip = retVal.Body.resultadoZip
            Return retVal.Body.GenerarTimbreLotePruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_ReportarCancelacionPrueba(ByVal request As WSFX.ReportarCancelacionPruebaRequest) As WSFX.ReportarCancelacionPruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.ReportarCancelacionPrueba
            Return MyBase.Channel.ReportarCancelacionPrueba(request)
        End Function
        
        Public Function ReportarCancelacionPrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.ReportarCancelacionPruebaRequest = New WSFX.ReportarCancelacionPruebaRequest()
            inValue.Body = New WSFX.ReportarCancelacionPruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.ReportarCancelacionPruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).ReportarCancelacionPrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.ReportarCancelacionPruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GenerarCFDIPrueba(ByVal request As WSFX.GenerarCFDIPruebaRequest) As WSFX.GenerarCFDIPruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GenerarCFDIPrueba
            Return MyBase.Channel.GenerarCFDIPrueba(request)
        End Function
        
        Public Function GenerarCFDIPrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GenerarCFDIPruebaRequest = New WSFX.GenerarCFDIPruebaRequest()
            inValue.Body = New WSFX.GenerarCFDIPruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GenerarCFDIPruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GenerarCFDIPrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GenerarCFDIPruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetAcuseRecepcionPrueba(ByVal request As WSFX.GetAcuseRecepcionPruebaRequest) As WSFX.GetAcuseRecepcionPruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GetAcuseRecepcionPrueba
            Return MyBase.Channel.GetAcuseRecepcionPrueba(request)
        End Function
        
        Public Function GetAcuseRecepcionPrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetAcuseRecepcionPruebaRequest = New WSFX.GetAcuseRecepcionPruebaRequest()
            inValue.Body = New WSFX.GetAcuseRecepcionPruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetAcuseRecepcionPruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetAcuseRecepcionPrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetAcuseRecepcionPruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetAcuseCancelacionPrueba(ByVal request As WSFX.GetAcuseCancelacionPruebaRequest) As WSFX.GetAcuseCancelacionPruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GetAcuseCancelacionPrueba
            Return MyBase.Channel.GetAcuseCancelacionPrueba(request)
        End Function
        
        Public Function GetAcuseCancelacionPrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetAcuseCancelacionPruebaRequest = New WSFX.GetAcuseCancelacionPruebaRequest()
            inValue.Body = New WSFX.GetAcuseCancelacionPruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetAcuseCancelacionPruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetAcuseCancelacionPrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetAcuseCancelacionPruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFX_TimbreFiscalDigitalSoap_GetIdSucursalPrueba(ByVal request As WSFX.GetIdSucursalPruebaRequest) As WSFX.GetIdSucursalPruebaResponse Implements WSFX.TimbreFiscalDigitalSoap.GetIdSucursalPrueba
            Return MyBase.Channel.GetIdSucursalPrueba(request)
        End Function
        
        Public Function GetIdSucursalPrueba(ByVal parametros As String, <System.Runtime.InteropServices.OutAttribute()> ByRef resultado As String) As Boolean
            Dim inValue As WSFX.GetIdSucursalPruebaRequest = New WSFX.GetIdSucursalPruebaRequest()
            inValue.Body = New WSFX.GetIdSucursalPruebaRequestBody()
            inValue.Body.parametros = parametros
            Dim retVal As WSFX.GetIdSucursalPruebaResponse = CType(Me,WSFX.TimbreFiscalDigitalSoap).GetIdSucursalPrueba(inValue)
            resultado = retVal.Body.resultado
            Return retVal.Body.GetIdSucursalPruebaResult
        End Function
    End Class
End Namespace
