'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace FacturaInteligente
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI", ConfigurationName:="FacturaInteligente.FI_TFDSoap")>  _
    Public Interface FI_TFDSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/TimbrarCFDIPrueba", ReplyAction:="*")>  _
        Function TimbrarCFDIPrueba(ByVal request As FacturaInteligente.TimbrarCFDIPruebaRequest) As FacturaInteligente.TimbrarCFDIPruebaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/TimbrarCFD", ReplyAction:="*")>  _
        Function TimbrarCFD(ByVal request As FacturaInteligente.TimbrarCFDRequest) As FacturaInteligente.TimbrarCFDResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/CancelarCFDI", ReplyAction:="*")>  _
        Function CancelarCFDI(ByVal request As FacturaInteligente.CancelarCFDIRequest) As FacturaInteligente.CancelarCFDIResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ConfirmarRecepcion", ReplyAction:="*")>  _
        Function ConfirmarRecepcion(ByVal request As FacturaInteligente.ConfirmarRecepcionRequest) As FacturaInteligente.ConfirmarRecepcionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ObtenerXML", ReplyAction:="*")>  _
        Function ObtenerXML(ByVal request As FacturaInteligente.ObtenerXMLRequest) As FacturaInteligente.ObtenerXMLResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ObtenerAcuseEnvio", ReplyAction:="*")>  _
        Function ObtenerAcuseEnvio(ByVal request As FacturaInteligente.ObtenerAcuseEnvioRequest) As FacturaInteligente.ObtenerAcuseEnvioResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ObtenerAcuseCancelacion", ReplyAction:="*")>  _
        Function ObtenerAcuseCancelacion(ByVal request As FacturaInteligente.ObtenerAcuseCancelacionRequest) As FacturaInteligente.ObtenerAcuseCancelacionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/CambiarPassword", ReplyAction:="*")>  _
        Function CambiarPassword(ByVal request As FacturaInteligente.CambiarPasswordRequest) As FacturaInteligente.CambiarPasswordResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ConsultarComplementoTimbre", ReplyAction:="*")>  _
        Function ConsultarComplementoTimbre(ByVal request As FacturaInteligente.ConsultarComplementoTimbreRequest) As FacturaInteligente.ConsultarComplementoTimbreResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ConsultarTimbrePorReferencia", ReplyAction:="*")>  _
        Function ConsultarTimbrePorReferencia(ByVal request As FacturaInteligente.ConsultarTimbrePorReferenciaRequest) As FacturaInteligente.ConsultarTimbrePorReferenciaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ConsultarEstadoComprobante", ReplyAction:="*")>  _
        Function ConsultarEstadoComprobante(ByVal request As FacturaInteligente.ConsultarEstadoComprobanteRequest) As FacturaInteligente.ConsultarEstadoComprobanteResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/ConsultarCreditos", ReplyAction:="*")>  _
        Function ConsultarCreditos(ByVal request As FacturaInteligente.ConsultarCreditosRequest) As FacturaInteligente.ConsultarCreditosResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.appfacturainteligente.com/WS-FI no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.appfacturainteligente.com/WS-FI/GeneraCBB", ReplyAction:="*")>  _
        Function GeneraCBB(ByVal request As FacturaInteligente.GeneraCBBRequest) As FacturaInteligente.GeneraCBBResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDIPruebaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFDIPrueba", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.TimbrarCFDIPruebaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.TimbrarCFDIPruebaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class TimbrarCFDIPruebaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cadenaXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.cadenaXML = cadenaXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDIPruebaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFDIPruebaResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.TimbrarCFDIPruebaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.TimbrarCFDIPruebaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class TimbrarCFDIPruebaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbrarCFDIPruebaResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbrarCFDIPruebaResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.TimbrarCFDIPruebaResult = TimbrarCFDIPruebaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFD", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.TimbrarCFDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.TimbrarCFDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class TimbrarCFDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cadenaXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public referencia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.cadenaXML = cadenaXML
            Me.referencia = referencia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFDResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.TimbrarCFDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.TimbrarCFDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class TimbrarCFDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbrarCFDResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbrarCFDResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.TimbrarCFDResult = TimbrarCFDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelarCFDI", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.CancelarCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.CancelarCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class CancelarCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RFCEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public listaCFDI As FacturaInteligente.ArrayOfString
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public certificadoPKCS12_Base64 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public passwordPKCS12 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal RFCEmisor As String, ByVal listaCFDI As FacturaInteligente.ArrayOfString, ByVal certificadoPKCS12_Base64 As String, ByVal passwordPKCS12 As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.RFCEmisor = RFCEmisor
            Me.listaCFDI = listaCFDI
            Me.certificadoPKCS12_Base64 = certificadoPKCS12_Base64
            Me.passwordPKCS12 = passwordPKCS12
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelarCFDIResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.CancelarCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.CancelarCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class CancelarCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CancelarCFDIResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelarCFDIResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.CancelarCFDIResult = CancelarCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmarRecepcionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmarRecepcion", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConfirmarRecepcionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConfirmarRecepcionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConfirmarRecepcionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmarRecepcionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmarRecepcionResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConfirmarRecepcionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConfirmarRecepcionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConfirmarRecepcionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConfirmarRecepcionResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConfirmarRecepcionResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ConfirmarRecepcionResult = ConfirmarRecepcionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerXML", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerXMLRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerXMLRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerXMLRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerXMLResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerXMLResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerXMLResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerXMLResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerXMLResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerXMLResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ObtenerXMLResult = ObtenerXMLResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseEnvioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseEnvio", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerAcuseEnvioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerAcuseEnvioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerAcuseEnvioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseEnvioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseEnvioResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerAcuseEnvioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerAcuseEnvioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerAcuseEnvioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerAcuseEnvioResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerAcuseEnvioResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ObtenerAcuseEnvioResult = ObtenerAcuseEnvioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseCancelacion", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerAcuseCancelacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerAcuseCancelacionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerAcuseCancelacionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseCancelacionResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ObtenerAcuseCancelacionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ObtenerAcuseCancelacionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ObtenerAcuseCancelacionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerAcuseCancelacionResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerAcuseCancelacionResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ObtenerAcuseCancelacionResult = ObtenerAcuseCancelacionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CambiarPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CambiarPassword", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.CambiarPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.CambiarPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class CambiarPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public passwordActual As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public passwordNuevo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.passwordActual = passwordActual
            Me.passwordNuevo = passwordNuevo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CambiarPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CambiarPasswordResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.CambiarPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.CambiarPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class CambiarPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CambiarPasswordResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CambiarPasswordResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.CambiarPasswordResult = CambiarPasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarComplementoTimbreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarComplementoTimbre", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarComplementoTimbreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarComplementoTimbreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarComplementoTimbreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarComplementoTimbreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarComplementoTimbreResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarComplementoTimbreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarComplementoTimbreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarComplementoTimbreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarComplementoTimbreResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarComplementoTimbreResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ConsultarComplementoTimbreResult = ConsultarComplementoTimbreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarTimbrePorReferenciaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarTimbrePorReferencia", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarTimbrePorReferenciaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarTimbrePorReferenciaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarTimbrePorReferenciaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RFCEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Referencia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.RFCEmisor = RFCEmisor
            Me.Referencia = Referencia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarTimbrePorReferenciaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarTimbrePorReferenciaResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarTimbrePorReferenciaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarTimbrePorReferenciaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarTimbrePorReferenciaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarTimbrePorReferenciaResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarTimbrePorReferenciaResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ConsultarTimbrePorReferenciaResult = ConsultarTimbrePorReferenciaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarEstadoComprobanteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarEstadoComprobante", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarEstadoComprobanteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarEstadoComprobanteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarEstadoComprobanteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarEstadoComprobanteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarEstadoComprobanteResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarEstadoComprobanteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarEstadoComprobanteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarEstadoComprobanteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarEstadoComprobanteResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarEstadoComprobanteResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ConsultarEstadoComprobanteResult = ConsultarEstadoComprobanteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarCreditosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarCreditos", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarCreditosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarCreditosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarCreditosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarCreditosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarCreditosResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.ConsultarCreditosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.ConsultarCreditosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class ConsultarCreditosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarCreditosResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarCreditosResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.ConsultarCreditosResult = ConsultarCreditosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GeneraCBBRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GeneraCBB", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.GeneraCBBRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.GeneraCBBRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class GeneraCBBRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RFCEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Referencia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.RFCEmisor = RFCEmisor
            Me.Referencia = Referencia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GeneraCBBResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GeneraCBBResponse", [Namespace]:="https://www.appfacturainteligente.com/WS-FI", Order:=0)>  _
        Public Body As FacturaInteligente.GeneraCBBResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FacturaInteligente.GeneraCBBResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.appfacturainteligente.com/WS-FI")>  _
    Partial Public Class GeneraCBBResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GeneraCBBResult As FacturaInteligente.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GeneraCBBResult As FacturaInteligente.ArrayOfString)
            MyBase.New
            Me.GeneraCBBResult = GeneraCBBResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FI_TFDSoapChannel
        Inherits FacturaInteligente.FI_TFDSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FI_TFDSoapClient
        Inherits System.ServiceModel.ClientBase(Of FacturaInteligente.FI_TFDSoap)
        Implements FacturaInteligente.FI_TFDSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_TimbrarCFDIPrueba(ByVal request As FacturaInteligente.TimbrarCFDIPruebaRequest) As FacturaInteligente.TimbrarCFDIPruebaResponse Implements FacturaInteligente.FI_TFDSoap.TimbrarCFDIPrueba
            Return MyBase.Channel.TimbrarCFDIPrueba(request)
        End Function
        
        Public Function TimbrarCFDIPrueba(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.TimbrarCFDIPruebaRequest = New FacturaInteligente.TimbrarCFDIPruebaRequest()
            inValue.Body = New FacturaInteligente.TimbrarCFDIPruebaRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.cadenaXML = cadenaXML
            Dim retVal As FacturaInteligente.TimbrarCFDIPruebaResponse = CType(Me,FacturaInteligente.FI_TFDSoap).TimbrarCFDIPrueba(inValue)
            Return retVal.Body.TimbrarCFDIPruebaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_TimbrarCFD(ByVal request As FacturaInteligente.TimbrarCFDRequest) As FacturaInteligente.TimbrarCFDResponse Implements FacturaInteligente.FI_TFDSoap.TimbrarCFD
            Return MyBase.Channel.TimbrarCFD(request)
        End Function
        
        Public Function TimbrarCFD(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.TimbrarCFDRequest = New FacturaInteligente.TimbrarCFDRequest()
            inValue.Body = New FacturaInteligente.TimbrarCFDRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.cadenaXML = cadenaXML
            inValue.Body.referencia = referencia
            Dim retVal As FacturaInteligente.TimbrarCFDResponse = CType(Me,FacturaInteligente.FI_TFDSoap).TimbrarCFD(inValue)
            Return retVal.Body.TimbrarCFDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_CancelarCFDI(ByVal request As FacturaInteligente.CancelarCFDIRequest) As FacturaInteligente.CancelarCFDIResponse Implements FacturaInteligente.FI_TFDSoap.CancelarCFDI
            Return MyBase.Channel.CancelarCFDI(request)
        End Function
        
        Public Function CancelarCFDI(ByVal usuario As String, ByVal password As String, ByVal RFCEmisor As String, ByVal listaCFDI As FacturaInteligente.ArrayOfString, ByVal certificadoPKCS12_Base64 As String, ByVal passwordPKCS12 As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.CancelarCFDIRequest = New FacturaInteligente.CancelarCFDIRequest()
            inValue.Body = New FacturaInteligente.CancelarCFDIRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.RFCEmisor = RFCEmisor
            inValue.Body.listaCFDI = listaCFDI
            inValue.Body.certificadoPKCS12_Base64 = certificadoPKCS12_Base64
            inValue.Body.passwordPKCS12 = passwordPKCS12
            Dim retVal As FacturaInteligente.CancelarCFDIResponse = CType(Me,FacturaInteligente.FI_TFDSoap).CancelarCFDI(inValue)
            Return retVal.Body.CancelarCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ConfirmarRecepcion(ByVal request As FacturaInteligente.ConfirmarRecepcionRequest) As FacturaInteligente.ConfirmarRecepcionResponse Implements FacturaInteligente.FI_TFDSoap.ConfirmarRecepcion
            Return MyBase.Channel.ConfirmarRecepcion(request)
        End Function
        
        Public Function ConfirmarRecepcion(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ConfirmarRecepcionRequest = New FacturaInteligente.ConfirmarRecepcionRequest()
            inValue.Body = New FacturaInteligente.ConfirmarRecepcionRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            Dim retVal As FacturaInteligente.ConfirmarRecepcionResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ConfirmarRecepcion(inValue)
            Return retVal.Body.ConfirmarRecepcionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ObtenerXML(ByVal request As FacturaInteligente.ObtenerXMLRequest) As FacturaInteligente.ObtenerXMLResponse Implements FacturaInteligente.FI_TFDSoap.ObtenerXML
            Return MyBase.Channel.ObtenerXML(request)
        End Function
        
        Public Function ObtenerXML(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ObtenerXMLRequest = New FacturaInteligente.ObtenerXMLRequest()
            inValue.Body = New FacturaInteligente.ObtenerXMLRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As FacturaInteligente.ObtenerXMLResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ObtenerXML(inValue)
            Return retVal.Body.ObtenerXMLResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ObtenerAcuseEnvio(ByVal request As FacturaInteligente.ObtenerAcuseEnvioRequest) As FacturaInteligente.ObtenerAcuseEnvioResponse Implements FacturaInteligente.FI_TFDSoap.ObtenerAcuseEnvio
            Return MyBase.Channel.ObtenerAcuseEnvio(request)
        End Function
        
        Public Function ObtenerAcuseEnvio(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ObtenerAcuseEnvioRequest = New FacturaInteligente.ObtenerAcuseEnvioRequest()
            inValue.Body = New FacturaInteligente.ObtenerAcuseEnvioRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As FacturaInteligente.ObtenerAcuseEnvioResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ObtenerAcuseEnvio(inValue)
            Return retVal.Body.ObtenerAcuseEnvioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ObtenerAcuseCancelacion(ByVal request As FacturaInteligente.ObtenerAcuseCancelacionRequest) As FacturaInteligente.ObtenerAcuseCancelacionResponse Implements FacturaInteligente.FI_TFDSoap.ObtenerAcuseCancelacion
            Return MyBase.Channel.ObtenerAcuseCancelacion(request)
        End Function
        
        Public Function ObtenerAcuseCancelacion(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ObtenerAcuseCancelacionRequest = New FacturaInteligente.ObtenerAcuseCancelacionRequest()
            inValue.Body = New FacturaInteligente.ObtenerAcuseCancelacionRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As FacturaInteligente.ObtenerAcuseCancelacionResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ObtenerAcuseCancelacion(inValue)
            Return retVal.Body.ObtenerAcuseCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_CambiarPassword(ByVal request As FacturaInteligente.CambiarPasswordRequest) As FacturaInteligente.CambiarPasswordResponse Implements FacturaInteligente.FI_TFDSoap.CambiarPassword
            Return MyBase.Channel.CambiarPassword(request)
        End Function
        
        Public Function CambiarPassword(ByVal Usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.CambiarPasswordRequest = New FacturaInteligente.CambiarPasswordRequest()
            inValue.Body = New FacturaInteligente.CambiarPasswordRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.passwordActual = passwordActual
            inValue.Body.passwordNuevo = passwordNuevo
            Dim retVal As FacturaInteligente.CambiarPasswordResponse = CType(Me,FacturaInteligente.FI_TFDSoap).CambiarPassword(inValue)
            Return retVal.Body.CambiarPasswordResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ConsultarComplementoTimbre(ByVal request As FacturaInteligente.ConsultarComplementoTimbreRequest) As FacturaInteligente.ConsultarComplementoTimbreResponse Implements FacturaInteligente.FI_TFDSoap.ConsultarComplementoTimbre
            Return MyBase.Channel.ConsultarComplementoTimbre(request)
        End Function
        
        Public Function ConsultarComplementoTimbre(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ConsultarComplementoTimbreRequest = New FacturaInteligente.ConsultarComplementoTimbreRequest()
            inValue.Body = New FacturaInteligente.ConsultarComplementoTimbreRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            Dim retVal As FacturaInteligente.ConsultarComplementoTimbreResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ConsultarComplementoTimbre(inValue)
            Return retVal.Body.ConsultarComplementoTimbreResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ConsultarTimbrePorReferencia(ByVal request As FacturaInteligente.ConsultarTimbrePorReferenciaRequest) As FacturaInteligente.ConsultarTimbrePorReferenciaResponse Implements FacturaInteligente.FI_TFDSoap.ConsultarTimbrePorReferencia
            Return MyBase.Channel.ConsultarTimbrePorReferencia(request)
        End Function
        
        Public Function ConsultarTimbrePorReferencia(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ConsultarTimbrePorReferenciaRequest = New FacturaInteligente.ConsultarTimbrePorReferenciaRequest()
            inValue.Body = New FacturaInteligente.ConsultarTimbrePorReferenciaRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.RFCEmisor = RFCEmisor
            inValue.Body.Referencia = Referencia
            Dim retVal As FacturaInteligente.ConsultarTimbrePorReferenciaResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ConsultarTimbrePorReferencia(inValue)
            Return retVal.Body.ConsultarTimbrePorReferenciaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ConsultarEstadoComprobante(ByVal request As FacturaInteligente.ConsultarEstadoComprobanteRequest) As FacturaInteligente.ConsultarEstadoComprobanteResponse Implements FacturaInteligente.FI_TFDSoap.ConsultarEstadoComprobante
            Return MyBase.Channel.ConsultarEstadoComprobante(request)
        End Function
        
        Public Function ConsultarEstadoComprobante(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ConsultarEstadoComprobanteRequest = New FacturaInteligente.ConsultarEstadoComprobanteRequest()
            inValue.Body = New FacturaInteligente.ConsultarEstadoComprobanteRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            Dim retVal As FacturaInteligente.ConsultarEstadoComprobanteResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ConsultarEstadoComprobante(inValue)
            Return retVal.Body.ConsultarEstadoComprobanteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_ConsultarCreditos(ByVal request As FacturaInteligente.ConsultarCreditosRequest) As FacturaInteligente.ConsultarCreditosResponse Implements FacturaInteligente.FI_TFDSoap.ConsultarCreditos
            Return MyBase.Channel.ConsultarCreditos(request)
        End Function
        
        Public Function ConsultarCreditos(ByVal Usuario As String, ByVal Password As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.ConsultarCreditosRequest = New FacturaInteligente.ConsultarCreditosRequest()
            inValue.Body = New FacturaInteligente.ConsultarCreditosRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            Dim retVal As FacturaInteligente.ConsultarCreditosResponse = CType(Me,FacturaInteligente.FI_TFDSoap).ConsultarCreditos(inValue)
            Return retVal.Body.ConsultarCreditosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FacturaInteligente_FI_TFDSoap_GeneraCBB(ByVal request As FacturaInteligente.GeneraCBBRequest) As FacturaInteligente.GeneraCBBResponse Implements FacturaInteligente.FI_TFDSoap.GeneraCBB
            Return MyBase.Channel.GeneraCBB(request)
        End Function
        
        Public Function GeneraCBB(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String) As FacturaInteligente.ArrayOfString
            Dim inValue As FacturaInteligente.GeneraCBBRequest = New FacturaInteligente.GeneraCBBRequest()
            inValue.Body = New FacturaInteligente.GeneraCBBRequestBody()
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.RFCEmisor = RFCEmisor
            inValue.Body.Referencia = Referencia
            Dim retVal As FacturaInteligente.GeneraCBBResponse = CType(Me,FacturaInteligente.FI_TFDSoap).GeneraCBB(inValue)
            Return retVal.Body.GeneraCBBResult
        End Function
    End Class
End Namespace
